@extends('layouts.app')

@section('title', 'Terms of Service | Postryx AI')
@section('meta_description', 'Terms and conditions governing the use of the Postryx AI viral content and programmatic SEO SaaS platform.')

@section('content')

<section style="padding: 70px 24px 80px; max-width: 860px; margin: 0 auto;">
    <h1 style="font-size: clamp(32px, 4vw, 44px); font-weight: 800; color: #fff; margin-bottom: 12px;">Terms of Service</h1>
    <div style="font-size: 13px; color: var(--text-muted); margin-bottom: 30px;">Last updated: August 24, 2026</div>

    <div class="glass-panel" style="padding: 36px; line-height: 1.8; color: #cbd5e1; font-size: 15px;">
        <h2 style="font-size: 20px; color: #fff; margin: 24px 0 12px;">1. Agreement to Terms</h2>
        <p>By accessing or using Postryx AI (located at postryx.in), you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not use our services.</p>

        <h2 style="font-size: 20px; color: #fff; margin: 24px 0 12px;">2. AI Content Generation &amp; Ownership</h2>
        <p>All content generated by users through Postryx AI tools, including social media posts, headlines, video scripts, and SEO articles, is 100% owned by the user. You hold full commercial rights to publish, modify, and monetize the generated output.</p>

        <h2 style="font-size: 20px; color: #fff; margin: 24px 0 12px;">3. Subscriptions &amp; Billing</h2>
        <p>Paid subscriptions (Starter, Pro Growth, Agency) are billed on a recurring monthly or annual basis. You may cancel your subscription at any time directly through your account dashboard.</p>

        <h2 style="font-size: 20px; color: #fff; margin: 24px 0 12px;">4. 14-Day Refund Policy</h2>
        <p>We provide a full 14-day money-back guarantee on all new subscriptions if you are unsatisfied with the platform for any reason.</p>

        <h2 style="font-size: 20px; color: #fff; margin: 24px 0 12px;">5. Contact Us</h2>
        <p>For support or inquiries regarding these terms, please contact us at: <strong style="color:#fff;">hello@postryx.in</strong>.</p>
    </div>
</section>

@endsection
